# 1. İçinde Python olan bir sistem seç
FROM python:3.11

# 2. Sunucu içinde bir çalışma klasörü oluştur
WORKDIR /code

# 3. Kütüphane listeni kopyala ve yükle
COPY ./requirements.txt /code/requirements.txt
RUN pip install --no-cache-dir --upgrade -r /code/requirements.txt

# 4. Kodlarını ve modelini içeri aktar
COPY . .

# 5. Hugging Face'in istediği 7860 portunda API'yi başlat
CMD ["uvicorn", "api:app", "--host", "0.0.0.0", "--port", "7860"]